apiVersion: v1
kind: ConfigMap
metadata:
  name: blockid-config
  namespace: blockid
  labels:
    app: blockid
data:
  SOLANA_CLUSTER: "mainnet"
  BLOCKID_TEST_MODE: "0"
  BLOCKID_USE_DUMMY_DATA: "0"
  CONFIDENCE_THRESHOLD: "0.72"
  DB_PATH: "/app/data/blockid.db"
