apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockid-data
  namespace: blockid
  labels:
    app: blockid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard  # uncomment for GKE/EKS
